//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearnBug.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factor
    {
        public int Id { get; set; }
        public int userId { get; set; }
        public int contentId { get; set; }
        public System.DateTime Datetime { get; set; }
        public double Price { get; set; }
        public int Commission { get; set; }
    
        public virtual Content Content { get; set; }
        public virtual User User { get; set; }
    }
}
